`fix`: ci

diff --git a/.github/workflows/django-tests.yaml b/.github/workflows/django-tests.yaml
--- a/.github/workflows/django-tests.yaml
+++ b/.github/workflows/django-tests.yaml
@@ -2,36 +2,35 @@ name: Django Tests CI
 
 on:
   push:
-    branches:
-      - main
+    branches: [ master ]
 
 jobs:
   lint-and-test:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.11
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.11
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r djangopdfmaker/requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r djangopdfmaker/requirements.txt
 
-    - name: Run Flake8
-      run: |
-        error_count=$(flake8 . --count --config tox.ini)
+      - name: Run Flake8
+        run: |
+          error_count=$(flake8 . --count --config tox.ini)
 
-        if [ $error_count -gt 0 ]; then
-          echo "Flake8 found $error_count errors."
-          exit 1
-        fi
+          if [ $error_count -gt 0 ]; then
+            echo "Flake8 found $error_count errors."
+            exit 1
+          fi
 
-    - name: Run tests
-      run: |
-        python manage.py test
+      - name: Run tests
+        run: |
+          python manage.py test
